/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlPanel.java
 *
 * Created on Oct 4, 2011, 2:17:28 PM
 */
package views;

import javax.swing.DefaultListModel;
import model.Model;

/**
 *
 * @author gq114c
 */
public class DirectoryKeywordPanel extends javax.swing.JPanel implements IUpdateView {

    private Model model;
    private DefaultListModel listModel;

    /** Creates new form ControlPanel */
    public DirectoryKeywordPanel() {
	initComponents();
	updateView(); 
    }

    public DirectoryKeywordPanel(Model model) {
	this.model = model;
	initComponents();
	listModel = new DefaultListModel();
	updateView(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DirectoryList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        removeKeyword = new javax.swing.JButton();
        keyWordToAdd = new javax.swing.JTextField();
        addKeyWord = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        DirectoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(DirectoryList);

        jLabel1.setText("Directory Names To Search:");

        removeKeyword.setText("Remove Selected Directory");
        removeKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeKeywordActionPerformed(evt);
            }
        });

        keyWordToAdd.setText("Videos");

        addKeyWord.setText("Add Directory");
        addKeyWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKeyWordActionPerformed(evt);
            }
        });

        jLabel2.setText("Directory Keyword:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addKeyWord)
                            .addComponent(keyWordToAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(removeKeyword))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keyWordToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addKeyWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeKeyword))
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addKeyWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKeyWordActionPerformed
	model.getSearchKeywords().add(keyWordToAdd.getText());
	updateView();
    }//GEN-LAST:event_addKeyWordActionPerformed

    private void removeKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeKeywordActionPerformed
	String selectedVal = (String) DirectoryList.getSelectedValue();
	model.getSearchKeywords().remove(selectedVal);
	updateView();

    }//GEN-LAST:event_removeKeywordActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList DirectoryList;
    private javax.swing.JButton addKeyWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keyWordToAdd;
    private javax.swing.JButton removeKeyword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
	listModel.removeAllElements();
	for (String s : model.getSearchKeywords()) {
	    listModel.addElement(s);
	}
	DirectoryList.setModel(listModel);
    }
}
