/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormatPanel.java
 *
 * Created on Oct 4, 2011, 3:59:32 PM
 */
package views;

import javax.swing.DefaultListModel;
import model.Model;

/**
 *
 * @author gq114c
 */
public class FormatPanel extends javax.swing.JPanel implements IUpdateView {

    Model model;
    private DefaultListModel listModel;

    /** Creates new form FormatPanel */
    public FormatPanel() {
	this.model = null;
	initComponents();

    }

    public FormatPanel(Model m) {
	listModel = new DefaultListModel();
	this.model = m;
	initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        formatList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        addFormat = new javax.swing.JButton();
        removeSelectedFormat = new javax.swing.JButton();
        formatToAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        formatList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(formatList);

        jLabel1.setText("Formats To Search For: ");

        addFormat.setText("Add Format");
        addFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormatActionPerformed(evt);
            }
        });

        removeSelectedFormat.setText("Remove Format");
        removeSelectedFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSelectedFormatActionPerformed(evt);
            }
        });

        formatToAdd.setText("jpg");
        formatToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatToAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Format Extension:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1)
                        .addComponent(removeSelectedFormat))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formatToAdd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addFormat, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeSelectedFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formatToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFormat)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeSelectedFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectedFormatActionPerformed
	model.getSearchFormats().remove((String) formatList.getSelectedValue());
	updateView();
    }//GEN-LAST:event_removeSelectedFormatActionPerformed

    private void addFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormatActionPerformed
	model.getSearchFormats().add(formatToAdd.getText());
	updateView();

    }//GEN-LAST:event_addFormatActionPerformed

    private void formatToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatToAddActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_formatToAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFormat;
    private javax.swing.JList formatList;
    private javax.swing.JTextField formatToAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeSelectedFormat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
	listModel.removeAllElements();
	for (String s : model.getSearchFormats()) {
	    listModel.addElement(s);
	}
	formatList.setModel(listModel);
    }
}
